language: python
python:
  - "3.6"

cache: pip
install:
  - pip install -r requirements.txt
  - pip install --editable . 
  - pip install halo

jobs:
  include:
    - stage: Installing plugins
      name: "Installing plugins"
      script:
       - cd plugins
       - bash install_all.sh
       - cd ..

    - stage: Running Unit Tests 
      name: "Unit Tests"
      script:
        - pytest
        
    - stage: Deploy
      name: "Deploying to Development"
      if: branch = development
      script:
        - echo $TRAVIS_COMMIT