name: raven
channels:
    - defaults
dependencies:
  - python=3.6.8
  - pip:
    - click==7.0
    - click-plugins==1.0.4
    - questionary==1.0.2
    - tqdm==4.31.1
    - pytest==4.3.0
    - boto3==1.8.7
    - pip-tools
    - moto==1.3.7
