dataset: click_test
overwrite_local: True
artifact_path: '~/Desktop/test'
# ec2_kill: True
metadata:
    created_by: Carson Schubert
    comments: no thanks
plugin:
    verbose: true
    comet: false
    model: ssd_mobilenet_v2_coco
    optimizer: RMSProp
    # NOTE: if use_default_config is true, hyperparameters are IGNORED
    use_default_config: true
    hyperparameters:
        train_steps: 1000
    