dataset: carson_instance_tester
overwrite_local: True
artifact_path: '~/Desktop/test'
# ec2_kill: True
metadata:
    created_by: Carson Schubert
    comments: no thanks
plugin:
    verbose: true
    comet: false
    model: mask_rcnn_inception_v2_coco # only one supported rn
    optimizer: Momentum # only one supported rn
    use_default_config: false
    no_validate: true
    